### ISSUE TITLE
New Docker Image Report "srt serve error code=6006"

### ISSUE THREAD

**Issue by treedom** [ossrs/srs-stack#132]
**Describe the bug**
![image](https://github.com/ossrs/srs-stack/assets/5617501/453f53c0-910e-4535-bdd8-28aec82ed049)

**Version**
docker run --rm -p 2022:2022 -p 2443:2443 -p 1935:1935/tcp -p 1985:1985/tcp \
  -p 8080:8080/tcp -p 8000:8000/udp -p 10080:10080/udp --name srs-stack \
  -v $HOME/db:/data ossrs/srs-stack:5
<img width="1021" alt="image" src="https://github.com/ossrs/srs-stack/assets/5617501/1a550c78-14c4-45b8-9f9e-03739766c997">

**To Reproduce**
1. docker run --rm -p 2022:2022 -p 2443:2443 -p 1935:1935/tcp -p 1985:1985/tcp \
  -p 8080:8080/tcp -p 8000:8000/udp -p 10080:10080/udp --name srs-stack \
  -v $HOME/db:/data ossrs/srs-stack:5

2. Use OBS To Set SRT Addr:
![image](https://github.com/ossrs/srs-stack/assets/5617501/cba057e0-9050-4ccf-8104-0c13c008d35b)

3. Press "Begin Living" In OBS

4. See Connect Error In OBS and The Error Msg Above : srt serve error code=6006

**Expected behavior**
A bout 2 month ago the srt living feature is work.

**Screenshots**
None

**Additional context**
None

**Comment by winlinvip** [comment]
Fixed in [v5.7.20+](https://github.com/ossrs/srs-stack/releases/tag/publication-v5.7.20)
