### ISSUE TITLE
play error 

### ISSUE THREAD

**Issue by huihuiyule** [ossrs/srs-stack#144]
**Describe the bug**

**v5.10.11**
Desribe your SRS Stack version here.
docker run -it --rm -v /home/live/srs-stack/data:/data -p 2022:2022/tcp -p 443:2443/tcp -p 1935:1935/tcp -p 1985:1985/tcp -p 80:8080/tcp -p 8000:8000/udp -p 10080:10080/udp -it --name srs-stack  ossrs/srs-stack:v5.10.11

**To Reproduce**
1. When accessing via https://, the displayed address is 127.0.0.1 and it is followed by http.
2. Certificate application shows a 500 error.
3. The player page fails to load, unable to play.

**Expected behavior**

**Screenshots**
![image](https://github.com/ossrs/srs-stack/assets/8141979/659352e2-ac63-4c33-86c6-2bf8e1d17767)

**Additional context**

`TRANS_BY_GPT4`

**Comment by huihuiyule** [comment]
![image](https://github.com/ossrs/srs-stack/assets/8141979/9972d1dc-cd52-4d59-98c9-7f820c10fa8b)
播放器页面 提示
Refused to execute script from 'https://live.xxxxxx.xxx/players/js/jquery-1.12.2.min.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.
srs_player.html:1  Refused to execute script from 'https://live.xxxxxx.xxx/players/js/mpegts-1.7.3.min.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.
srs_player.html:1  Refused to execute script from 'https://live.xxxxxx.xxx/players/js/dash-v4.5.1.all.min.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.
 
os:  Ubuntu 22.04.3 LTS

**Comment by winlinvip** [comment]
感谢反馈，是因为缺失某些js文件，导致404，识别未text/plain。

Fixed in v5.10.16

**Comment by huihuiyule** [comment]
When accessing via https://, the displayed address is 127.0.0.1 and it is followed by http.

**Comment by winlinvip** [comment]
请不要使用 SRS Stack中的Console播放流，而应该使用SRS Stack中的链接播放流。因为Console是SRS的一个简单控制台，未来会全部放在SRS Stack中实现。
