### ISSUE TITLE
 I have encountered two minor issues while using the Docker version:

### ISSUE THREAD

**Issue by wuxianlijiang** [ossrs/srs-stack#145]
The live streaming transcoding function is excellent, thank you to the developers. I have encountered two minor issues while using the Docker version:
1. It only supports one-way transcoding.
2. If two or more live streams are pushed to the server simultaneously after transcoding is enabled, the Docker displays red error messages.

**Comment by winlinvip** [comment]
可以启动多个docker，就可以支持多路转码，参考 https://ossrs.io/lts/en-us/faq-srs-stack#multiple-instances
