### ISSUE TITLE
[Question] Fail to publish stream via https

### ISSUE THREAD

**Issue by dieuhuy9199** [ossrs/srs-stack#156]
Sorry for my English, I use srs-stack for livestreaming video, I deployed to AWS EC2, opened the port according to the instructions (8000/udp, using WebRTC - WHIP) and with http it runs fine, but after pointing the domain and configuring https with let's encrypt , the domain name has been accessed but when I published the stream I received this error (Image below). Am I missing any steps?

<img width="1263" alt="Screenshot 2024-01-22 at 9 34 29 AM" src="https://github.com/ossrs/srs-stack/assets/157333942/ac731c77-d20d-455f-b20e-54be8d48b4f0">

<img width="1263" alt="Screenshot 2024-01-22 at 9 34 29 AM" src="https://github.com/ossrs/srs-stack/assets/157333942/8a33de02-0137-448f-9dff-fd7a4e559ab3">

**Comment by winlinvip** [comment]
你可以选择中文版本，Issue可以用中文提交，会自动翻译。

回到你的问题，你是否完成了Usage第一步：开放UDP 8000端口，是否可以用网页打开WHIP推流？

**Comment by dieuhuy9199** [comment]
> You can choose the Chinese version, and issues can be submitted in Chinese; they will be automatically translated.
> 
> Returning to your question, have you completed the first step under Usage: opening UDP port 8000, and are you able to open WHIP streaming through a web page?
> 
> `TRANS_BY_GPT4`

I have solved it. I realized my domain is configured  through Cloudflare, I tried editing the DNS record to "DNS Only" instead of "Proxied" and it worked. I will close this issue, thanks for replying

**Comment by winlinvip** [comment]
是的，如果你选择CF的`Proxied`模式，那么CF会托管这个域名的所有流量，那么UDP 8000肯定是不能用的，选择`DNS Only`就可以了。
