### ISSUE TITLE
AI Transcript acceleration by FFmpeg GPU support

### ISSUE THREAD

**Issue by limjoe** [ossrs/srs-stack#159]
**What is the business background? Please provide a description.**
AI transcript task is slow, especially ffmpeg encode part, so the transcript live stream with subtitle delay a lot.

**Is your feature request related to a problem? Please describe.**
Large delay and poor user experience

**Describe the solution you'd like**
AI transcript support GPU for ffmpeg encode, for example NVIDIA GPU for accelerate.

**Describe alternatives you've considered**
1. Use a better CPU
2. Use low-resolution video streaming

**Additional context**
![image](https://github.com/ossrs/srs-stack/assets/1276784/d2b4284a-8eaa-4ca5-9b1f-b259e974ad71)

**Comment by fonty37** [comment]
ffmpeg -hwaccel cuda -i input.ts -vf "subtitles=subtitles.srt:force_style='Alignment=2,MarginV=20',hwupload_cuda" -c:v h264_nvenc -profile:v main -preset medium -rc:v vbr -cq:v 19 -bf 0 -acodec aac -copyts -y output.ts

**Comment by winlinvip** [comment]
You are now able to setup the video codec parameters for transcript.

![Image](https://github.com/ossrs/srs-stack/assets/2777660/4cd0706a-980f-4b03-bc7a-ff8efe493a75)

Strongly recommand setting the `-bt 0` to be compatible with both live stream and WebRTC.

**Comment by winlinvip** [comment]
Fixed in v5.14.11
